/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedNeedsRouteImport } from './routes/_authenticated/needs'
import { Route as AuthenticatedNeedNeedIdRouteImport } from './routes/_authenticated/need.$needId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNeedsRoute = AuthenticatedNeedsRouteImport.update({
  id: '/needs',
  path: '/needs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNeedNeedIdRoute = AuthenticatedNeedNeedIdRouteImport.update({
  id: '/need/$needId',
  path: '/need/$needId',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/needs': typeof AuthenticatedNeedsRoute
  '/need/$needId': typeof AuthenticatedNeedNeedIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/needs': typeof AuthenticatedNeedsRoute
  '/need/$needId': typeof AuthenticatedNeedNeedIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/needs': typeof AuthenticatedNeedsRoute
  '/_authenticated/need/$needId': typeof AuthenticatedNeedNeedIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/needs' | '/need/$needId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/needs' | '/need/$needId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/needs'
    | '/_authenticated/need/$needId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/needs': {
      id: '/_authenticated/needs'
      path: '/needs'
      fullPath: '/needs'
      preLoaderRoute: typeof AuthenticatedNeedsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/need/$needId': {
      id: '/_authenticated/need/$needId'
      path: '/need/$needId'
      fullPath: '/need/$needId'
      preLoaderRoute: typeof AuthenticatedNeedNeedIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedNeedsRoute: typeof AuthenticatedNeedsRoute
  AuthenticatedNeedNeedIdRoute: typeof AuthenticatedNeedNeedIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedNeedsRoute: AuthenticatedNeedsRoute,
  AuthenticatedNeedNeedIdRoute: AuthenticatedNeedNeedIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
